apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk # rootpassword
  username: YXBwdXNlcg== # appuser
  password: YXBwcGFzc3dvcmQ= # apppassword
  database: Y3J1ZF9kYg== # crud_db
